### ISSUE TITLE
'/mnt/storage/projects/AQFx/ftp.ptree.jaxa.jp/... Not found

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/air-health-bushfire-smoke-controller#4]
@MilesSowden I get the following warning

cp: cannot stat '/mnt/storage/projects/AQFx/ftp.ptree.jaxa.jp/pub/himawari/L2/ARP/030/aot_2020010606.nc': No such file or directory

**Comment by MilesSowden** [comment]
External storage not plugged in

 

From: Ivan Hanigan ***@***.***> 
Sent: Monday, February 6, 2023 5:37 PM
To: cardat/air-health-bushfire-smoke-controller ***@***.***>
Cc: MilesSowden ***@***.***>; Mention ***@***.***>
Subject: [cardat/air-health-bushfire-smoke-controller] '/mnt/storage/projects/AQFx/ftp.ptree.jaxa.jp/... Not found (Issue #4)

 

@MilesSowden <https://github.com/MilesSowden>  I get the following warning

cp: cannot stat '/mnt/storage/projects/AQFx/ftp.ptree.jaxa.jp/pub/himawari/L2/ARP/030/aot_2020010606.nc': No such file or directory

**Comment by ivanhanigan** [comment]
Can this file be on tower?  I think all required data should be on the tower to run the workflow - is that right?

**Comment by ivanhanigan** [comment]
@MilesSowden @bushtecho The external storage is plugged in again but has not automounted.  Can @MilesSowden do this via command line

**Comment by ivanhanigan** [comment]
@MilesSowden

**Comment by MilesSowden** [comment]
@ivanhanigan , thanks for your question. To answer your concern, I have checked and confirmed that the external drive and the file (/mnt/storage/projects/AQFx/ftp.ptree.jaxa.jp/pub/himawari/L2/ARP/030/aot_2020010606.nc) are working fine. We could move the file to the tower (e.g., /hdd/projects/AQFx/JAXA) so that all required data are present in one place to run the workflow. However, this raises some questions regarding the management of temporary files and where to store the deep dive dataset. Shall we discuss this further at tomorrow's meeting and decide on the best course of action?

**Comment by ivanhanigan** [comment]
@MilesSowden Thanks and sorry I missed the meeting last week.  You raise an important point about data storage.  I guess that the external drive solution will be fine for our pilot work on the tower and the datasets will be transferred to the main server (or is already there) so in that case the data are in the shared location in the production server.  We may just leave the solution in the pilot workspace on the tower as it is.  @bushtecho I am linking to you so you can coordinate our data storage issues. Thanks.

**Comment by bushtecho** [comment]
Happy to, we could discuss this today

**Comment by ivanhanigan** [comment]
This issue remains relevant as long as we are working on the Z-tower but is closed when we move code to GADI

**Comment by ivanhanigan** [comment]
This issue remains relevant fpr working on the Z-tower but is closed now we are moving code to GADI
