### ISSUE TITLE
setup: github housekeeping

### ISSUE THREAD

**Issue by ivanhanigan** [cardat/air-health-bushfire-smoke-controller#8]

**Comment by MilesSowden** [comment]
I created folders and moved files around.
Some work still required for housekeeping, will make changes once the extra stats request is given @jamiu-cic I may leave some of the housekeeping for you (parallelization) and cleanup so that you may have a better handle on the real-time system.
@ivanhanigan do you want to move your GLC files?

**Comment by jamiu-cic** [comment]
@ivanhanigan @MilesSowden @bushtecho @cassandrayuen I have just created a branch named "**testing_jamiu**' as a playground for my testing and possible code optimisation. I will discuss any changes I make with you before merging to the '**main**' if satisfactory.

**Comment by jamiu-cic** [comment]
@MilesSowden @ivanhanigan I am currently working on the overall README.md for this project. Are you able to help me with the sequence of running the codes in this repo? That would be helpful in my description of the data processing pipeline.
